### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by NicoRenaud** [bnikolic/simpleredcal#1]
Hi @bnikolic 

thanks for the great code ! We are trying to see if we could use part of it and since we are not part of the hera consortium we do not have access to the data. Do you if it would be possible to somehow gain access the dataset you are using in [SimpleRedCal.ipynb](https://github.com/bnikolic/simpleredcal/blob/master/examples/SimpleRedCal.ipynb) ? 

Thanks !

**Comment by bnikolic** [comment]
Hi @NicoRenaud sorry for the very late reply...  I will need to check about the HERA data, generally they haven't been released in the past. will let you know. @matyasmolnar wrote most of this code  has just completed his PhD. If it is of interest he can I'm sure send you his thesis.

**Comment by NicoRenaud** [comment]
Thanks for the answer ! I've managed to work directly with hera_cal and the data contained there for the testing. I should have closed the issue but I forgot about it sorry. Thanks again !
